apiVersion: v1
kind: Pod
metadata:
  name: test-pod-nfs-direct
  labels:
   app: testing-ability-to-run-a-pod-with-nfs-directly
spec:
  containers:
  - name: love-yourself-directly
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo you are appriciated on $(date); sleep 10;done"]
    volumeMounts:
    - mountPath: /data
      name: nfs-vol
  volumes:
   - name: nfs-vol
     nfs:
       server: 10.8.0.1
       path: "/volume1/k8s"

