apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /volume1/k8s
    server: 10.8.0.1 
  persistentVolumeReclaimPolicy: Recycle  
